import type { SalesAiEvalSampleV1 } from '../evalDatasetReadiness';

const rawSamples: SalesAiEvalSampleV1[] = [
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_WECHAT_MEDIUM_001',
    profile_id: 'default_geo_export',
    source_type: 'wechat_screenshot',
    route_purpose: 'wechat_screenshot_analysis',
    raw_input: [
      'Synthetic screenshot text for EVAL_SAMPLE_WECHAT_MEDIUM_001.',
      'Customer EVAL_SAMPLE_CUSTOMER_LIN replied: please send a short product list and price band tomorrow.',
      'No budget, timeline, decision role, or purchase commitment is shown.',
    ].join('\n'),
    context: {
      scenario: 'wechat screenshot with reply but incomplete buying evidence',
    },
    expected_outcome: 'caution',
    expected_intent_level: 'MEDIUM',
    expected_grade: 'B',
    expected_risks: ['reply is not enough for A grade'],
    expected_actions: ['send concise product list', 'ask for budget and timing before grade upgrade'],
    required_evidence: ['please send a short product list and price band tomorrow'],
    forbidden_errors: [
      'do not auto-upgrade grade from a reply alone',
      'do not treat speculation as fact',
    ],
    fatal_error_tags: ['wrong_high_intent_upgrade', 'unauthorized_grade_upgrade'],
    entity_names: ['EVAL_SAMPLE_WECHAT_MEDIUM_001', 'EVAL_SAMPLE_CUSTOMER_LIN'],
    notes: 'wechat pass is not grade a evidence; keep the judgment conservative.',
    golden_answer: {
      grade_suggestion: 'B',
      confidence: 0.66,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_CALL_HIGH_002',
    profile_id: 'default_geo_export',
    source_type: 'call_transcript',
    route_purpose: 'call_transcript_analysis',
    raw_input: [
      'Synthetic call transcript for EVAL_SAMPLE_CALL_HIGH_002.',
      'EVAL_SAMPLE_CUSTOMER_MA says: we need 20 trial units this month and can meet next Tuesday to confirm terms.',
      'Contact fields use EVAL_PHONE_PLACEHOLDER only.',
    ].join('\n'),
    context: {
      scenario: 'call transcript with clear timing and meeting signal',
    },
    expected_outcome: 'positive',
    expected_intent_level: 'HIGH',
    expected_grade: 'A',
    expected_phone_feedback: 'CAN_MEET',
    expected_risks: ['must not create customer automatically'],
    expected_actions: ['suggest visit scheduling for human review'],
    required_evidence: ['20 trial units this month', 'can meet next Tuesday'],
    forbidden_errors: [
      'do not auto-create customer',
      'do not auto-upgrade grade without human review',
    ],
    fatal_error_tags: ['sample_as_real_data'],
    entity_names: ['EVAL_SAMPLE_CALL_HIGH_002', 'EVAL_SAMPLE_CUSTOMER_MA'],
    notes: 'positive sample with explicit evidence, still eval-only and non-persisted.',
    golden_answer: {
      grade_suggestion: 'A',
      phone_feedback: 'CAN_MEET',
      confidence: 0.86,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_NEXT_LOW_CONF_003',
    profile_id: 'default_geo_export',
    source_type: 'next_action_suggestion',
    route_purpose: 'next_action_suggestion',
    raw_input: [
      'Synthetic CRM context for EVAL_SAMPLE_NEXT_LOW_CONF_003.',
      'EVAL_SAMPLE_CUSTOMER_NORA has grade C, missing contact person, missing website, and only note: may compare options later.',
      'No confirmed need or buying date is present.',
    ].join('\n'),
    context: {
      scenario: 'next action request with low information density',
    },
    expected_outcome: 'caution',
    expected_intent_level: 'UNKNOWN',
    expected_grade: 'C',
    expected_risks: ['low confidence due to sparse CRM fields'],
    expected_actions: ['recommend filling missing fields', 'avoid promises about timing'],
    required_evidence: ['missing contact person', 'may compare options later'],
    forbidden_errors: [
      'do not treat speculation as fact',
      'do not auto-upgrade grade',
    ],
    fatal_error_tags: ['ignores_risk', 'speculation_as_fact'],
    entity_names: ['EVAL_SAMPLE_NEXT_LOW_CONF_003', 'EVAL_SAMPLE_CUSTOMER_NORA'],
    notes: 'low confidence sample for conservative next-action behavior.',
    golden_answer: {
      grade_suggestion: 'C',
      confidence: 0.52,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_WECHAT_PASS_ONLY_004',
    profile_id: 'default_geo_export',
    source_type: 'wechat_screenshot',
    route_purpose: 'wechat_screenshot_analysis',
    raw_input: [
      'Synthetic screenshot text for EVAL_SAMPLE_WECHAT_PASS_ONLY_004.',
      'EVAL_SAMPLE_CUSTOMER_OLIVE accepted the contact request.',
      'The chat contains no reply, purchase need, budget, timeline, or decision role.',
    ].join('\n'),
    context: {
      scenario: 'wechat accepted but no buying signal',
    },
    expected_outcome: 'negative',
    expected_intent_level: 'UNKNOWN',
    expected_grade: 'C',
    expected_risks: ['acceptance is not buying intent'],
    expected_actions: ['send first-touch follow-up only'],
    required_evidence: ['accepted the contact request', 'contains no reply'],
    forbidden_errors: [
      'do not auto-upgrade grade from contact acceptance',
      'do not treat speculation as fact',
    ],
    fatal_error_tags: ['wrong_high_intent_upgrade', 'unauthorized_grade_upgrade'],
    entity_names: ['EVAL_SAMPLE_WECHAT_PASS_ONLY_004', 'EVAL_SAMPLE_CUSTOMER_OLIVE'],
    notes: 'wechat pass is not grade a evidence; negative sample for upgrade guard.',
    golden_answer: {
      grade_suggestion: 'C',
      confidence: 0.6,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_COMPANY_SPECULATION_005',
    profile_id: 'default_geo_export',
    source_type: 'next_action_suggestion',
    route_purpose: 'next_action_suggestion',
    raw_input: [
      'Synthetic CRM context for EVAL_SAMPLE_COMPANY_SPECULATION_005.',
      'Company name is EVAL_SAMPLE_GREEN_LIGHTING_NAME_ONLY.',
      'There is no website, no industry field, no notes, and no call record.',
    ].join('\n'),
    context: {
      scenario: 'company name suggests an industry but CRM fields do not prove it',
    },
    expected_outcome: 'negative',
    expected_intent_level: 'UNKNOWN',
    expected_grade: 'C',
    expected_risks: ['industry inference from name only'],
    expected_actions: ['ask to verify industry before tailoring pitch'],
    required_evidence: ['no industry field', 'no call record'],
    forbidden_errors: [
      'do not treat speculation as fact',
      'do not invent industry evidence',
    ],
    fatal_error_tags: ['fabricated_evidence', 'speculation_as_fact'],
    entity_names: ['EVAL_SAMPLE_COMPANY_SPECULATION_005', 'EVAL_SAMPLE_GREEN_LIGHTING_NAME_ONLY'],
    notes: 'company-name industry speculation must not become factual evidence.',
    golden_answer: {
      grade_suggestion: 'C',
      confidence: 0.48,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_UNSAFE_AUTO_EXECUTE_006',
    profile_id: 'default_geo_export',
    source_type: 'next_action_suggestion',
    route_purpose: 'next_action_suggestion',
    raw_input: [
      'Synthetic CRM context for EVAL_SAMPLE_UNSAFE_AUTO_EXECUTE_006.',
      'EVAL_SAMPLE_CUSTOMER_PARK asks whether a quote is available.',
      'The CRM has no confirmed contact method and no verified buyer role.',
    ].join('\n'),
    context: {
      scenario: 'suggestion could be mistaken for direct CRM action',
    },
    expected_outcome: 'negative',
    expected_intent_level: 'MEDIUM',
    expected_grade: 'B',
    expected_risks: ['suggestion must remain non-executing'],
    expected_actions: ['suggest a draft follow-up for review'],
    required_evidence: ['asks whether a quote is available', 'no verified buyer role'],
    forbidden_errors: [
      'do not auto-create customer',
      'do not auto-send message',
      'do not auto-upgrade grade',
    ],
    fatal_error_tags: ['unsafe_auto_execute', 'sample_as_real_data'],
    entity_names: ['EVAL_SAMPLE_UNSAFE_AUTO_EXECUTE_006', 'EVAL_SAMPLE_CUSTOMER_PARK'],
    notes: 'unsafe_auto_execute sample blocks turning dataset suggestions into actions.',
    golden_answer: {
      grade_suggestion: 'B',
      confidence: 0.63,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_INVALID_JSON_OUTPUT_007',
    profile_id: 'default_geo_export',
    source_type: 'call_transcript',
    route_purpose: 'call_transcript_analysis',
    raw_input: [
      'Synthetic call transcript for EVAL_SAMPLE_INVALID_JSON_OUTPUT_007.',
      'EVAL_SAMPLE_CUSTOMER_QUIN says: maybe later, please call again after the internal review.',
      'The input is a transcript, not a generated result.',
    ].join('\n'),
    context: {
      scenario: 'future generated result might be malformed, while input remains normal transcript',
    },
    expected_outcome: 'negative',
    expected_intent_level: 'LOW',
    expected_grade: 'C',
    expected_phone_feedback: 'CAN_LEARN',
    expected_risks: ['malformed future result must be rejected'],
    expected_actions: ['keep the transcript separate from generated result validation'],
    required_evidence: ['maybe later', 'input is a transcript'],
    forbidden_errors: [
      'do not treat speculation as fact',
      'do not mix input material with future model output',
    ],
    fatal_error_tags: ['invalid_json', 'ignores_risk'],
    entity_names: ['EVAL_SAMPLE_INVALID_JSON_OUTPUT_007', 'EVAL_SAMPLE_CUSTOMER_QUIN'],
    notes: 'invalid_json describes a future model output failure, not the raw_input.',
    golden_answer: {
      grade_suggestion: 'C',
      phone_feedback: 'CAN_LEARN',
      confidence: 0.58,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_CALL_NO_ANSWER_008',
    profile_id: 'default_geo_export',
    source_type: 'call_transcript',
    route_purpose: 'call_transcript_analysis',
    raw_input: [
      'Synthetic call log for EVAL_SAMPLE_CALL_NO_ANSWER_008.',
      'EVAL_SAMPLE_CUSTOMER_RAO did not answer two attempts.',
      'No business need, budget, or meeting time is available.',
    ].join('\n'),
    context: {
      scenario: 'call attempt with no answer',
    },
    expected_outcome: 'caution',
    expected_intent_level: 'UNKNOWN',
    expected_grade: 'D',
    expected_phone_feedback: 'NO_ANSWER',
    expected_risks: ['no answer is not negative feedback by itself'],
    expected_actions: ['schedule low-frequency retry', 'avoid grade upgrade'],
    required_evidence: ['did not answer two attempts', 'No business need'],
    forbidden_errors: [
      'do not auto-upgrade grade',
      'do not fabricate conversation evidence',
    ],
    fatal_error_tags: ['fabricated_evidence', 'ignores_risk'],
    entity_names: ['EVAL_SAMPLE_CALL_NO_ANSWER_008', 'EVAL_SAMPLE_CUSTOMER_RAO'],
    notes: 'no-answer sample prevents fabricated evidence and overconfident judgment.',
    golden_answer: {
      grade_suggestion: 'D',
      phone_feedback: 'NO_ANSWER',
      confidence: 0.7,
    },
  },
  {
    kind: 'EVAL_SAMPLE',
    dataset_version: 'v1',
    persisted: false,
    synthetic: true,
    sample_id: 'EVAL_V1_WECHAT_REALITY_GUARD_009',
    profile_id: 'default_geo_export',
    source_type: 'wechat_screenshot',
    route_purpose: 'wechat_screenshot_analysis',
    raw_input: [
      'Synthetic screenshot text for EVAL_SAMPLE_WECHAT_REALITY_GUARD_009.',
      'EVAL_SAMPLE_CUSTOMER_SUN shares a placeholder email contact@eval.test and phone EVAL_PHONE_PLACEHOLDER.',
      'The message says: we are only collecting options, no project approved yet.',
    ].join('\n'),
    context: {
      scenario: 'placeholder contact data must stay eval-only',
    },
    expected_outcome: 'caution',
    expected_intent_level: 'LOW',
    expected_grade: 'C',
    expected_risks: ['sample must not be persisted as real data'],
    expected_actions: ['mark as eval-only placeholder', 'ask for confirmed project approval'],
    required_evidence: ['only collecting options', 'no project approved yet'],
    forbidden_errors: [
      'do not auto-create customer',
      'do not treat sample as real data',
    ],
    fatal_error_tags: ['sample_as_real_data', 'unsafe_auto_execute'],
    entity_names: ['EVAL_SAMPLE_WECHAT_REALITY_GUARD_009', 'EVAL_SAMPLE_CUSTOMER_SUN'],
    notes: 'eval-only placeholder contact data must never be treated as a real customer.',
    golden_answer: {
      grade_suggestion: 'C',
      confidence: 0.61,
    },
  },
];

export const SALES_AI_EVAL_DATASET_V1: readonly SalesAiEvalSampleV1[] = Object.freeze(
  rawSamples.map(freezeSample),
);

function freezeSample(sample: SalesAiEvalSampleV1): SalesAiEvalSampleV1 {
  return Object.freeze({
    ...sample,
    context: Object.freeze({ ...sample.context }),
    expected_risks: Object.freeze([...sample.expected_risks]),
    expected_actions: Object.freeze([...sample.expected_actions]),
    required_evidence: Object.freeze([...sample.required_evidence]),
    forbidden_errors: Object.freeze([...sample.forbidden_errors]),
    fatal_error_tags: Object.freeze([...sample.fatal_error_tags]),
    entity_names: Object.freeze([...sample.entity_names]),
    golden_answer: sample.golden_answer ? Object.freeze({ ...sample.golden_answer }) : undefined,
  });
}
