export const FINAL_USABILITY_CHANGED_FILES = [
  'src-tauri/Cargo.toml',
  'src-tauri/src/bin/migrate_plaintext_credentials.rs',
  'src-tauri/src/credential_migration.rs',
  'src-tauri/src/encrypted_credentials.rs',
  'src-tauri/src/lib.rs',
  'src-tauri/src/secure_credentials.rs',
  'src-tauri/src/trusted_host.rs',
  'src/__tests__/actionRunnerBoundaryContract.readiness.test.ts',
  'src/__tests__/ai.test.ts',
  'src/__tests__/confirmedActionContract.readiness.test.ts',
  'src/__tests__/confirmedActionLiveDryRun.readiness.test.ts',
  'src/__tests__/confirmedActionReviewQueue.readiness.test.ts',
  'src/__tests__/customer-priority-ranking.focused.test.ts',
  'src/__tests__/dashboardDataProjection.readiness.test.ts',
  'src/__tests__/dashboardProjectionPanel.readiness.test.ts',
  'src/__tests__/dbWritePlanDryRun.readiness.test.ts',
  'src/__tests__/encrypted-sql-credential.focused.test.ts',
  'src/__tests__/finalUsabilityChangedFileCohort.ts',
  'src/__tests__/humanConfirmationContract.readiness.test.ts',
  'src/__tests__/intent-envelope-single-source.test.ts',
  'src/__tests__/legacyCredentialMigration.focused.test.ts',
  'src/__tests__/liveProviderSandboxCall.readiness.test.ts',
  'src/__tests__/liveSandboxToSuggestOnlyBridge.readiness.test.ts',
  'src/__tests__/manualLiveProviderSmokeGate.readiness.test.ts',
  'src/__tests__/modelProviderBoundaryContract.readiness.test.ts',
  'src/__tests__/modelProviderReadOnlySandbox.readiness.test.ts',
  'src/__tests__/modelReadOnlyInvocationGate.readiness.test.ts',
  'src/__tests__/modelRouterRuntime.readiness.test.ts',
  'src/__tests__/modelSuggestOnlyOutputGate.readiness.test.ts',
  'src/__tests__/modelSuggestionAdapterBoundary.readiness.test.ts',
  'src/__tests__/modelSuggestionReviewDraftGate.readiness.test.ts',
  'src/__tests__/no-rag-boundary.focused.test.ts',
  'src/__tests__/pending-instruction-resume.focused.test.ts',
  'src/__tests__/productionMockLeakage.focused.test.ts',
  'src/__tests__/readOnlyAISuggestionPanel.readiness.test.ts',
  'src/__tests__/readOnlyAISuggestionService.readiness.test.ts',
  'src/__tests__/readOnlyAgent.readiness.test.ts',
  'src/__tests__/readOnlyAgentLiveDryRun.readiness.test.ts',
  'src/__tests__/readOnlyAgentSnapshotAdapter.readiness.test.ts',
  'src/__tests__/readOnlySnapshotLoader.readiness.test.ts',
  'src/__tests__/reviewDraftQueueBoundary.readiness.test.ts',
  'src/__tests__/safeWriteRunnerGate.readiness.test.ts',
  'src/__tests__/secretBoundary.focused.test.ts',
  'src/__tests__/semantic-router-adapter.test.ts',
  'src/__tests__/semantic-search-synonyms.focused.test.ts',
  'src/__tests__/semanticRouterProductionWiring.focused.test.ts',
  'src/__tests__/stage10SalesAgentOperatingLayer.test.ts',
  'src/__tests__/suggestOnlyAgent.readiness.test.ts',
  'src/__tests__/textAIProvider.test.ts',
  'src/__tests__/trustedHostBoundary.test.ts',
  'src/__tests__/trustedHostProvider.focused.test.ts',
  'src/components/aiNative/SalesAgentInteractionWorkspace.tsx',
  'src/lib/ai.ts',
  'src/lib/db.ts',
  'src/lib/modelCapabilities/trustedHost.ts',
  'src/lib/multimodalProvider.ts',
  'src/lib/productionAi/capabilityRoutingMatrix.ts',
  'src/lib/productionAi/semanticIntentRouter.ts',
  'src/lib/salesAgentTools/agentIntentEnvelope.ts',
  'src/lib/salesAgentTools/customerPriorityRanking.ts',
  'src/lib/salesAgentTools/filterNormalization.ts',
  'src/lib/salesAgentTools/interactionController.ts',
  'src/lib/salesAgentTools/registry.ts',
  'src/lib/salesAgentTools/trustedHostAdapter.ts',
  'src/lib/textAIProvider.ts',
  'src/pages/AISettingsPage.tsx',
] as const;

export const FINAL_USABILITY_TRACKED_CHANGED_FILES = [
  'src-tauri/Cargo.toml',
  'src-tauri/src/credential_migration.rs',
  'src-tauri/src/lib.rs',
  'src-tauri/src/secure_credentials.rs',
  'src-tauri/src/trusted_host.rs',
  'src/__tests__/actionRunnerBoundaryContract.readiness.test.ts',
  'src/__tests__/ai.test.ts',
  'src/__tests__/confirmedActionContract.readiness.test.ts',
  'src/__tests__/confirmedActionLiveDryRun.readiness.test.ts',
  'src/__tests__/confirmedActionReviewQueue.readiness.test.ts',
  'src/__tests__/dashboardDataProjection.readiness.test.ts',
  'src/__tests__/dashboardProjectionPanel.readiness.test.ts',
  'src/__tests__/dbWritePlanDryRun.readiness.test.ts',
  'src/__tests__/humanConfirmationContract.readiness.test.ts',
  'src/__tests__/intent-envelope-single-source.test.ts',
  'src/__tests__/legacyCredentialMigration.focused.test.ts',
  'src/__tests__/liveProviderSandboxCall.readiness.test.ts',
  'src/__tests__/liveSandboxToSuggestOnlyBridge.readiness.test.ts',
  'src/__tests__/manualLiveProviderSmokeGate.readiness.test.ts',
  'src/__tests__/modelProviderBoundaryContract.readiness.test.ts',
  'src/__tests__/modelProviderReadOnlySandbox.readiness.test.ts',
  'src/__tests__/modelReadOnlyInvocationGate.readiness.test.ts',
  'src/__tests__/modelRouterRuntime.readiness.test.ts',
  'src/__tests__/modelSuggestOnlyOutputGate.readiness.test.ts',
  'src/__tests__/modelSuggestionAdapterBoundary.readiness.test.ts',
  'src/__tests__/modelSuggestionReviewDraftGate.readiness.test.ts',
  'src/__tests__/productionMockLeakage.focused.test.ts',
  'src/__tests__/readOnlyAISuggestionPanel.readiness.test.ts',
  'src/__tests__/readOnlyAISuggestionService.readiness.test.ts',
  'src/__tests__/readOnlyAgent.readiness.test.ts',
  'src/__tests__/readOnlyAgentLiveDryRun.readiness.test.ts',
  'src/__tests__/readOnlyAgentSnapshotAdapter.readiness.test.ts',
  'src/__tests__/readOnlySnapshotLoader.readiness.test.ts',
  'src/__tests__/reviewDraftQueueBoundary.readiness.test.ts',
  'src/__tests__/safeWriteRunnerGate.readiness.test.ts',
  'src/__tests__/secretBoundary.focused.test.ts',
  'src/__tests__/semantic-router-adapter.test.ts',
  'src/__tests__/semanticRouterProductionWiring.focused.test.ts',
  'src/__tests__/stage10SalesAgentOperatingLayer.test.ts',
  'src/__tests__/suggestOnlyAgent.readiness.test.ts',
  'src/__tests__/textAIProvider.test.ts',
  'src/__tests__/trustedHostBoundary.test.ts',
  'src/__tests__/trustedHostProvider.focused.test.ts',
  'src/components/aiNative/SalesAgentInteractionWorkspace.tsx',
  'src/lib/ai.ts',
  'src/lib/db.ts',
  'src/lib/modelCapabilities/trustedHost.ts',
  'src/lib/multimodalProvider.ts',
  'src/lib/productionAi/capabilityRoutingMatrix.ts',
  'src/lib/productionAi/semanticIntentRouter.ts',
  'src/lib/salesAgentTools/agentIntentEnvelope.ts',
  'src/lib/salesAgentTools/filterNormalization.ts',
  'src/lib/salesAgentTools/interactionController.ts',
  'src/lib/salesAgentTools/registry.ts',
  'src/lib/salesAgentTools/trustedHostAdapter.ts',
  'src/lib/textAIProvider.ts',
  'src/pages/AISettingsPage.tsx',
] as const;

export const FINAL_USABILITY_SOURCE_CHANGED_FILES = [
  'src/__tests__/actionRunnerBoundaryContract.readiness.test.ts',
  'src/__tests__/ai.test.ts',
  'src/__tests__/confirmedActionContract.readiness.test.ts',
  'src/__tests__/confirmedActionLiveDryRun.readiness.test.ts',
  'src/__tests__/confirmedActionReviewQueue.readiness.test.ts',
  'src/__tests__/customer-priority-ranking.focused.test.ts',
  'src/__tests__/dashboardDataProjection.readiness.test.ts',
  'src/__tests__/dashboardProjectionPanel.readiness.test.ts',
  'src/__tests__/dbWritePlanDryRun.readiness.test.ts',
  'src/__tests__/encrypted-sql-credential.focused.test.ts',
  'src/__tests__/finalUsabilityChangedFileCohort.ts',
  'src/__tests__/humanConfirmationContract.readiness.test.ts',
  'src/__tests__/intent-envelope-single-source.test.ts',
  'src/__tests__/legacyCredentialMigration.focused.test.ts',
  'src/__tests__/liveProviderSandboxCall.readiness.test.ts',
  'src/__tests__/liveSandboxToSuggestOnlyBridge.readiness.test.ts',
  'src/__tests__/manualLiveProviderSmokeGate.readiness.test.ts',
  'src/__tests__/modelProviderBoundaryContract.readiness.test.ts',
  'src/__tests__/modelProviderReadOnlySandbox.readiness.test.ts',
  'src/__tests__/modelReadOnlyInvocationGate.readiness.test.ts',
  'src/__tests__/modelRouterRuntime.readiness.test.ts',
  'src/__tests__/modelSuggestOnlyOutputGate.readiness.test.ts',
  'src/__tests__/modelSuggestionAdapterBoundary.readiness.test.ts',
  'src/__tests__/modelSuggestionReviewDraftGate.readiness.test.ts',
  'src/__tests__/no-rag-boundary.focused.test.ts',
  'src/__tests__/pending-instruction-resume.focused.test.ts',
  'src/__tests__/productionMockLeakage.focused.test.ts',
  'src/__tests__/readOnlyAISuggestionPanel.readiness.test.ts',
  'src/__tests__/readOnlyAISuggestionService.readiness.test.ts',
  'src/__tests__/readOnlyAgent.readiness.test.ts',
  'src/__tests__/readOnlyAgentLiveDryRun.readiness.test.ts',
  'src/__tests__/readOnlyAgentSnapshotAdapter.readiness.test.ts',
  'src/__tests__/readOnlySnapshotLoader.readiness.test.ts',
  'src/__tests__/reviewDraftQueueBoundary.readiness.test.ts',
  'src/__tests__/safeWriteRunnerGate.readiness.test.ts',
  'src/__tests__/secretBoundary.focused.test.ts',
  'src/__tests__/semantic-router-adapter.test.ts',
  'src/__tests__/semantic-search-synonyms.focused.test.ts',
  'src/__tests__/semanticRouterProductionWiring.focused.test.ts',
  'src/__tests__/stage10SalesAgentOperatingLayer.test.ts',
  'src/__tests__/suggestOnlyAgent.readiness.test.ts',
  'src/__tests__/textAIProvider.test.ts',
  'src/__tests__/trustedHostBoundary.test.ts',
  'src/__tests__/trustedHostProvider.focused.test.ts',
  'src/components/aiNative/SalesAgentInteractionWorkspace.tsx',
  'src/lib/ai.ts',
  'src/lib/db.ts',
  'src/lib/modelCapabilities/trustedHost.ts',
  'src/lib/multimodalProvider.ts',
  'src/lib/productionAi/capabilityRoutingMatrix.ts',
  'src/lib/productionAi/semanticIntentRouter.ts',
  'src/lib/salesAgentTools/agentIntentEnvelope.ts',
  'src/lib/salesAgentTools/customerPriorityRanking.ts',
  'src/lib/salesAgentTools/filterNormalization.ts',
  'src/lib/salesAgentTools/interactionController.ts',
  'src/lib/salesAgentTools/registry.ts',
  'src/lib/salesAgentTools/trustedHostAdapter.ts',
  'src/lib/textAIProvider.ts',
  'src/pages/AISettingsPage.tsx',
] as const;

export const REGION_PORTFOLIO_QUERY_FIX_CHANGED_FILES = [
  'src/__tests__/semantic-search-synonyms.focused.test.ts',
  'src/__tests__/finalUsabilityChangedFileCohort.ts',
  'src/lib/salesAgentTools/filterNormalization.ts',
] as const;

function hasSameNormalizedFileSet(actualFiles: readonly string[], expectedFiles: readonly string[]): boolean {
  const actual = new Set(actualFiles.map(file => file.replace(/\\/g, '/').replace(/^local-crm-desktop\//, '')));
  const expected = new Set(expectedFiles);
  return actual.size === expected.size
    && [...actual].every(file => expected.has(file))
    && [...expected].every(file => actual.has(file));
}

export function hasExactFinalUsabilityChangedFileSet(actualFiles: readonly string[]): boolean {
  return hasSameNormalizedFileSet(actualFiles, FINAL_USABILITY_CHANGED_FILES)
    || hasSameNormalizedFileSet(actualFiles, FINAL_USABILITY_SOURCE_CHANGED_FILES)
    || hasSameNormalizedFileSet(actualFiles, REGION_PORTFOLIO_QUERY_FIX_CHANGED_FILES);
}

export function hasExactFinalUsabilityTrackedChangedFileSet(actualFiles: readonly string[]): boolean {
  return hasSameNormalizedFileSet(actualFiles, FINAL_USABILITY_TRACKED_CHANGED_FILES);
}
