import { describe, expect, it } from 'vitest';
import { buildContextSnapshot } from '../lib/context/contextBuilder';
import { buildCustomerMemoryContext } from '../lib/customerMemory';
import { executeSalesAgentReadTool, SALES_AGENT_CUSTOMER_SCOPED_TOOL_IDS, SALES_AGENT_TOOL_IDS } from '../lib/salesAgentTools/registry';
import { classifySalesAgentIntent, createSalesAgentDraft, proposeConfirmedCrmAction, proposeSalesAgentPlan, runSalesAgentInteraction, validateSalesAgentPlan } from '../lib/salesAgentTools/operatingLayer';
const context = buildContextSnapshot({ snapshotId: 'stage10-snapshot', capturedAt: '2026-07-12T00:00:00.000Z', timeWindow: { from: '2026-07-01T00:00:00.000Z', to: '2026-07-12T00:00:00.000Z' }, customers: [{ customerId: 'customer-1', name: 'Ada', grade: 'A', intentLevel: 'HIGH', observedAt: '2026-07-12T00:00:00.000Z', evidenceIds: ['customer-1'] }], accounts: [], interactions: [] });
const snapshot = { kind: 'LOADED_READ_ONLY_AGENT_SNAPSHOT', version: 'v1', snapshot_id: 'stage10', synthetic: false, persisted: true, load_source: 'sqlite_read_only', loaded_at: '2026-07-12T00:00:00.000Z', context: { active_profile_id: 'foreign_trade_geo', now: '2026-07-12T00:00:00.000Z' }, customers: [{ id: 'customer-1', name: 'Ada', customer_grade: 'A', intent_level: 'HIGH', evidence_ref: { type: 'customer', id: 'customer-1', label: 'Ada', synthetic: false, persisted: true } }], tasks: [], work_items: [], collected_leads: [], replay_evidence: [], import_rows: [], capture_events: [], prompt_plans: [], model_invocations: [], eval_summaries: [] } as const;
const memory = buildCustomerMemoryContext({ customer_id: 'customer-1', items: [{ memory_id: 'active-memory', customer_id: 'customer-1', kind: 'fact', summary: 'Prefers an evidence-backed follow-up.', source_kind: 'crm_record', validation_source: 'crm_record', source_reference: 'followup:1', evidence_reference: 'FOLLOW_UP_RECORD:followup-1', source_timestamp: '2026-07-12T00:00:00.000Z', recorded_at: '2026-07-12T00:00:00.000Z' }] });
describe('Stage10.5 Sales Agent intelligence polish', () => {
  it('uses only explicit read tools and preserves customer scope', () => {
    expect(SALES_AGENT_CUSTOMER_SCOPED_TOOL_IDS).toHaveLength(9);
    expect(SALES_AGENT_TOOL_IDS).toContain('search_customers');
    expect(SALES_AGENT_TOOL_IDS).toHaveLength(10);
    expect(executeSalesAgentReadTool('get_customer', { customer_id: 'customer-1', snapshot, context })).toMatchObject({ read_only: true, writes_crm: false, evidence_refs: ['customer-1'] });
  });
  it('maps distinct messages to distinct bounded plans and safely falls back for unknown intent', () => { const summary = proposeSalesAgentPlan('客户总结', 'customer-1'); const risk = proposeSalesAgentPlan('分析风险和机会', 'customer-1'); const fallback = proposeSalesAgentPlan('something unrelated', 'customer-1'); expect(summary.intent).toBe('CUSTOMER_SUMMARY'); expect(risk.intent).toBe('CUSTOMER_RISK_ANALYSIS'); expect(risk.steps.map(step => step.tool_id)).not.toEqual(summary.steps.map(step => step.tool_id)); expect(fallback).toMatchObject({ intent: 'SAFE_FALLBACK', safe_fallback: true }); [summary, risk, fallback].forEach(plan => expect(plan.steps.length).toBeLessThanOrEqual(5)); });
  it('rejects unknown tools and over-limit plans', () => { const plan = proposeSalesAgentPlan('Prepare me', 'customer-1'); expect(() => validateSalesAgentPlan({ ...plan, steps: [{ tool_id: 'unknown' as never, customer_id: 'customer-1' }] }, 'customer-1')).toThrow('unknown tool'); expect(() => validateSalesAgentPlan({ ...plan, steps: Array.from({ length: 6 }, () => plan.steps[0]) }, 'customer-1')).toThrow('one to five'); });
  it('carries active memory, preserves evidence, and keeps drafts/actions non-writing', async () => { const interaction = await runSalesAgentInteraction('准备跟进文案', { customer_id: 'customer-1', snapshot, context, memory, profile_id: 'foreign_trade_geo' }); const active = interaction.trace.find(item => item.tool_id === 'get_active_memory'); expect(active?.records).toHaveLength(1); expect(active?.records).toContainEqual(expect.objectContaining({ memory_id: 'active-memory' })); expect(interaction.response.evidence_refs).toContain('customer-1'); expect(createSalesAgentDraft('follow_up_wording', interaction)).toMatchObject({ requires_human_review: true, sent: false, written: false }); expect(proposeConfirmedCrmAction(interaction)).toMatchObject({ requires_human_confirmation: true, executable: false, writes_crm: false }); });
  it('never infers an unregistered intent or direct provider call', () => { expect(classifySalesAgentIntent('')).toBe('SAFE_FALLBACK'); expect(() => proposeSalesAgentPlan('', 'customer-1')).toThrow('user message'); });
});
