export const STAGE2_PHASE_0_5_CHANGED_FILES = [
  'src/components/aiNative/AINativeCRMWorkspace.tsx',
  'src/__tests__/actionRunnerBoundaryContract.readiness.test.ts',
  'src/__tests__/confirmedActionLiveDryRun.readiness.test.ts',
  'src/__tests__/confirmedActionReviewQueue.readiness.test.ts',
  'src/__tests__/dashboardDataProjection.readiness.test.ts',
  'src/__tests__/dashboardProjectionPanel.readiness.test.ts',
  'src/__tests__/dbWritePlanDryRun.readiness.test.ts',
  'src/__tests__/humanConfirmationContract.readiness.test.ts',
  'src/__tests__/liveProviderSandboxCall.readiness.test.ts',
  'src/__tests__/liveSandboxToSuggestOnlyBridge.readiness.test.ts',
  'src/__tests__/manualLiveProviderSmokeGate.readiness.test.ts',
  'src/__tests__/modelProviderBoundaryContract.readiness.test.ts',
  'src/__tests__/modelProviderReadOnlySandbox.readiness.test.ts',
  'src/__tests__/modelReadOnlyInvocationGate.readiness.test.ts',
  'src/__tests__/modelSuggestionAdapterBoundary.readiness.test.ts',
  'src/__tests__/modelSuggestionReviewDraftGate.readiness.test.ts',
  'src/__tests__/modelSuggestOnlyOutputGate.readiness.test.ts',
  'src/__tests__/readOnlyAISuggestionPanel.readiness.test.ts',
  'src/__tests__/readOnlyAISuggestionService.readiness.test.ts',
  'src/__tests__/reviewDraftQueueBoundary.readiness.test.ts',
  'src/__tests__/safeWriteRunnerGate.readiness.test.ts',
  'src/__tests__/stage2ChangedFileCohort.ts',
  'src/__tests__/stage2Phase0.contextProfiles.test.ts',
  'src/__tests__/stage2Phase1.eval.test.ts',
  'src/__tests__/stage2Phase2.reasoning.test.ts',
  'src/__tests__/stage2Phase3.aiJobs.test.ts',
  'src/__tests__/stage2Phase4.humanReview.test.ts',
  'src/__tests__/stage2Phase5.workspaceIntegration.test.ts',
  'src/components/aiNative/Stage2ArchitectureStatus.tsx',
  'src/lib/aiJobs/aiJobService.ts',
  'src/lib/aiJobs/inMemoryAIJobRepository.ts',
  'src/lib/aiJobs/types.ts',
  'src/lib/context/contextBuilder.ts',
  'src/lib/context/types.ts',
  'src/lib/context/workspaceContextAdapter.ts',
  'src/lib/eval/evaluationRunner.ts',
  'src/lib/eval/evidenceValidator.ts',
  'src/lib/eval/fixtures.ts',
  'src/lib/eval/types.ts',
  'src/lib/reasoning/humanReviewContract.ts',
  'src/lib/reasoning/reasoningContract.ts',
  'src/lib/reasoning/types.ts',
  'src/lib/verticalAIProfiles/profiles/feishuSaas.ts',
  'src/lib/verticalAIProfiles/profiles/foreignTradeGeo.ts',
  'src/lib/verticalAIProfiles/registry.ts',
  'src/lib/verticalAIProfiles/types.ts',
] as const;

export function hasExactStage2ChangedFileSet(changedFiles: readonly string[]): boolean {
  const expected = new Set<string>(STAGE2_PHASE_0_5_CHANGED_FILES);
  return changedFiles.length === expected.size && changedFiles.every(file => expected.has(file));
}
