export const LEAD_WORKBENCH_TABLE_SQL = [
  `CREATE TABLE IF NOT EXISTS lead_import_batches (
    id TEXT PRIMARY KEY,
    batch_name TEXT NOT NULL,
    batch_type TEXT NOT NULL,
    source_label TEXT,
    total_rows INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS lead_import_rows (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    row_index INTEGER NOT NULL,
    raw_data_json TEXT NOT NULL DEFAULT '{}',
    company_name TEXT,
    city TEXT,
    industry TEXT,
    website TEXT,
    contact_name TEXT,
    mobile TEXT,
    tel TEXT,
    email TEXT,
    score REAL,
    grade TEXT,
    tanji_search_keyword TEXT,
    matching_reason TEXT,
    priority_contact_role TEXT,
    source_evidence TEXT,
    decision TEXT NOT NULL DEFAULT 'RESERVE',
    decision_status TEXT NOT NULL DEFAULT 'PENDING',
    created_customer_id TEXT,
    created_work_item_id TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES lead_import_batches(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lead_work_items (
    id TEXT PRIMARY KEY,
    import_row_id TEXT,
    customer_id TEXT,
    work_type TEXT NOT NULL,
    company_name TEXT,
    city TEXT,
    industry TEXT,
    priority INTEGER NOT NULL DEFAULT 0,
    lookup_goal TEXT NOT NULL,
    tanji_search_keyword TEXT,
    status TEXT NOT NULL DEFAULT 'TODO',
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (import_row_id) REFERENCES lead_import_rows(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lead_capture_events (
    id TEXT PRIMARY KEY,
    work_item_id TEXT NOT NULL,
    raw_text TEXT NOT NULL,
    parsed_json TEXT NOT NULL DEFAULT '{}',
    confidence_json TEXT NOT NULL DEFAULT '{}',
    action TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (work_item_id) REFERENCES lead_work_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS collected_leads (
    id TEXT PRIMARY KEY,
    work_item_id TEXT,
    import_row_id TEXT,
    customer_id TEXT,
    company_name TEXT,
    contact_name TEXT,
    position TEXT,
    mobile TEXT,
    tel TEXT,
    website TEXT,
    email TEXT,
    raw_text TEXT,
    note TEXT,
    sync_status TEXT NOT NULL DEFAULT 'UNSYNCED',
    created_customer_id TEXT,
    updated_customer_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (work_item_id) REFERENCES lead_work_items(id),
    FOREIGN KEY (import_row_id) REFERENCES lead_import_rows(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lead_sync_logs (
    id TEXT PRIMARY KEY,
    collected_lead_id TEXT NOT NULL,
    action TEXT NOT NULL,
    target_customer_id TEXT,
    status TEXT NOT NULL,
    message TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (collected_lead_id) REFERENCES collected_leads(id),
    FOREIGN KEY (target_customer_id) REFERENCES customers(id)
  )`,
];

export const LEAD_WORKBENCH_INDEX_SQL = [
  'CREATE INDEX IF NOT EXISTS idx_lead_import_rows_batch_id ON lead_import_rows(batch_id)',
  'CREATE INDEX IF NOT EXISTS idx_lead_import_rows_decision_status ON lead_import_rows(decision_status)',
  'CREATE INDEX IF NOT EXISTS idx_lead_import_rows_company_name ON lead_import_rows(company_name)',
  'CREATE INDEX IF NOT EXISTS idx_lead_work_items_import_row_id ON lead_work_items(import_row_id)',
  'CREATE INDEX IF NOT EXISTS idx_lead_work_items_customer_id ON lead_work_items(customer_id)',
  'CREATE INDEX IF NOT EXISTS idx_lead_work_items_status ON lead_work_items(status)',
  'CREATE INDEX IF NOT EXISTS idx_lead_capture_events_work_item_id ON lead_capture_events(work_item_id)',
  'CREATE INDEX IF NOT EXISTS idx_collected_leads_work_item_id ON collected_leads(work_item_id)',
  'CREATE INDEX IF NOT EXISTS idx_collected_leads_import_row_id ON collected_leads(import_row_id)',
  'CREATE INDEX IF NOT EXISTS idx_collected_leads_customer_id ON collected_leads(customer_id)',
  'CREATE INDEX IF NOT EXISTS idx_collected_leads_sync_status ON collected_leads(sync_status)',
  'CREATE INDEX IF NOT EXISTS idx_lead_sync_logs_collected_lead_id ON lead_sync_logs(collected_lead_id)',
  'CREATE INDEX IF NOT EXISTS idx_lead_sync_logs_target_customer_id ON lead_sync_logs(target_customer_id)',
];
