import { useState } from 'react';
import type { ContextSnapshot } from '../../lib/context/types';
import type { CustomerMemoryContext } from '../../lib/customerMemory';
import type { LoadedReadOnlyAgentSnapshot } from '../../lib/readOnlySnapshotLoaderReadiness';
import { runSalesAgentInteraction, type SalesAgentInteractionResult } from '../../lib/salesAgentTools/operatingLayer';

const toolProgress: Record<string, string> = { get_customer: '客户基本情况', get_customer_context: '客户上下文', get_customer_timeline: '最近沟通记录', list_customer_followups: '跟进记录', list_customer_visits: '面访记录', list_customer_tasks: '待办事项', get_active_memory: '历史关键判断', get_existing_ai_results: '已有 AI 结果', get_today_priority: '当前优先级' };

export function SalesAgentInteractionWorkspace({ customerId, snapshot, context, memory, profileId }: { customerId: string; snapshot: LoadedReadOnlyAgentSnapshot; context: ContextSnapshot; memory?: CustomerMemoryContext; profileId: string }) {
  const [message, setMessage] = useState(''); const [result, setResult] = useState<SalesAgentInteractionResult | null>(null); const [state, setState] = useState<'idle' | 'loading' | 'blocked' | 'error'>('idle'); const [error, setError] = useState('');
  const submit = async () => { setState('loading'); setError(''); try { setResult(await runSalesAgentInteraction(message, { customer_id: customerId, snapshot, context, memory, profile_id: profileId })); setState('idle'); } catch (cause) { setState(message.trim() ? 'error' : 'blocked'); setError(cause instanceof Error ? cause.message : String(cause)); } };
  return <section className="card" aria-label="Sales Agent interaction workspace"><h3 className="section-title">Sales Agent</h3><p>Current customer and ACTIVE memory are fixed from this workspace. Tools are read-only; drafts require review; no CRM write or automatic execution.</p><textarea aria-label="Sales Agent message" value={message} onChange={event => setMessage(event.target.value)} placeholder="Ask for a customer assessment or preparation draft." rows={3} style={{ width: '100%' }} /><button className="btn btn-primary" onClick={() => void submit()} disabled={state === 'loading'}>{state === 'loading' ? 'Reasoning…' : 'Ask Sales Agent'}</button>{(state === 'blocked' || state === 'error') && <p role="alert">{error}</p>}{result && <div><p><strong>Human review required.</strong> Drafts are not sent or written.</p><p>正在分析：{result.trace.map(item => `✓ ${toolProgress[item.tool_id]}`).join(' · ')}</p><h4>Customer understanding</h4><p>{result.response.customer_understanding}</p><h4>Recent changes</h4><p>{result.response.recent_changes}</p><h4>Risks / opportunities</h4><p>{result.response.risks_and_opportunities}</p><h4>Recommended next step</h4><p>{result.response.recommended_next_step}</p><p>Evidence: {result.response.evidence_refs.join(', ') || 'No evidence returned'}</p></div>}</section>;
}
