import { useMemo, useState } from 'react';
import type { ContextSnapshot } from '../../lib/context/types'; import type { CustomerMemoryContext, MemoryRepository } from '../../lib/customerMemory'; import type { LoadedReadOnlyAgentSnapshot } from '../../lib/readOnlySnapshotLoaderReadiness';
import { SalesAgentSession, type AgentSessionResult, type SalesAgentHost, type SafeWriteBoundary } from '../../lib/salesAgentTools/agentSession'; import { approvedCrmWriteBoundary } from '../../lib/salesAgentTools/approvedCrmWriteBoundary'; import type { AgentWriteProposal } from '../../lib/salesAgentTools/confirmedWrite'; import { editFact, reviewedFacts, setFactReview, type CustomerCaptureReview } from '../../lib/customerCapture/review';

/** Production controller used by the confirmation card; refresh is only after an approved successful write. */
export async function confirmSalesAgentProposal(session: SalesAgentSession, proposal: AgentWriteProposal, onRefresh: () => Promise<void>, boundary: SafeWriteBoundary = approvedCrmWriteBoundary) {
  const result = await session.confirmWrite(proposal, { proposal_id: proposal.proposal_id, proposal_hash: proposal.proposal_hash, tool_id: proposal.tool_id, customer_id: proposal.customer_id, entity_id: proposal.entity_id, payload_hash: proposal.proposal_hash, nonce: proposal.nonce ?? '', confirmed_at: new Date().toISOString() }, boundary);
  await onRefresh();
  return result;
}

export function SalesAgentInteractionWorkspace({ customerId, snapshot, context, memory, profileId, host, memoryRepository, loadCustomerSnapshot, onRefresh }: { customerId: string; snapshot: LoadedReadOnlyAgentSnapshot; context: ContextSnapshot; memory?: CustomerMemoryContext; profileId: string; host: SalesAgentHost | null; memoryRepository?: MemoryRepository; loadCustomerSnapshot: (customerId: string) => Promise<{ next_follow_up_at: string | null } | null>; onRefresh: () => Promise<void> }) {
  const session = useMemo(() => new SalesAgentSession(customerId, host, () => new Date().toISOString(), { snapshot, context, memory, profile_id: profileId, memory_repository: memoryRepository, loadCustomerSnapshot }), [customerId, host, snapshot, context, memory, profileId, memoryRepository, loadCustomerSnapshot]);
  const [message, setMessage] = useState(''); const [result, setResult] = useState<AgentSessionResult | null>(null); const [captureText, setCaptureText] = useState(''); const [imagePreview, setImagePreview] = useState(''); const [captureReview, setCaptureReview] = useState<CustomerCaptureReview | null>(null); const [proposal, setProposal] = useState<AgentWriteProposal | null>(null); const [writeResult, setWriteResult] = useState(''); const [editing, setEditing] = useState<Record<string, string>>({}); const [state, setState] = useState<'idle' | 'reasoning' | 'capturing' | 'blocked' | 'error'>('idle'); const [error, setError] = useState('');
  const submit = async () => { setState('reasoning'); setError(''); const outcome = await session.submit(message, result?.evidence_refs); if (outcome.kind === 'reasoning_result') setResult(outcome.result); else if (outcome.kind === 'write_proposal') setProposal(outcome.proposal); else setError(outcome.reason); setState('idle'); };
  const confirm = async () => { if (!proposal) return; try { const write = await confirmSalesAgentProposal(session, proposal, onRefresh); setWriteResult(`Success: ${write.entity_id} (${write.fields.join(', ')}) · refreshed customer context`); setProposal(null); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const analyzeCapture = async (sourceType: 'text' | 'image', source: string) => { setState('capturing'); setError(''); try { setCaptureReview(await session.capture(sourceType, source)); setState('idle'); } catch (cause) { setState('blocked'); setError(cause instanceof Error ? cause.message : String(cause)); } };
  const analyzeReviewed = async () => { if (!captureReview) return; try { await session.persistReviewedFacts(captureReview); setResult(await session.analyzeReviewedFacts(captureReview)); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  return <section className="card" aria-label="Sales Agent interaction workspace"><h3 className="section-title">Sales Agent</h3><p>Scope: customer <strong>{customerId}</strong> · Profile: {profileId} · Host: {host ? 'trusted host adapter' : 'blocked'} · No provider call or write occurs on page load.</p><textarea aria-label="Sales Agent message" value={message} onChange={event => setMessage(event.target.value)} rows={3} style={{ width: '100%' }} /><button className="btn btn-primary" onClick={() => void submit()} disabled={state !== 'idle' || !message.trim()}>Ask Sales Agent</button>{error && <p role="alert">{error}</p>}
    <div aria-label="Sales Agent conversation">{session.messages.map(item => <p key={item.id}><strong>{item.role} ({item.mode}):</strong> {item.content}</p>)}</div>{result && <div aria-label="Sales Agent result"><p>Provider/model: {result.provider} / {result.model}</p><p>Intent: {result.plan.intent} · Confidence: {result.confidence}</p><p>Plan: {result.plan.steps.map(step => step.tool_id).join(' → ')}</p><p>Tool trace: {result.tool_trace.map(trace => `${trace.tool_id}: ${trace.records.length} records`).join(' · ')}</p><p>{result.response}</p><p>Evidence: {result.evidence_refs.join(', ')}</p><p>Human review required; not executable; no CRM write.</p></div>}
    {proposal && <section className="card" aria-label="Exact CRM confirmation"><h4>Confirm exact CRM operation</h4><p>Proposal: {proposal.proposal_id}</p><p>Customer/entity: {proposal.customer_id} / {proposal.entity_type}</p><p>Operation: {proposal.tool_id} ({proposal.operation})</p><p>Current: {JSON.stringify(proposal.current_values)}</p><p>Proposed: {JSON.stringify(proposal.proposed_values)}</p><p>Reason: {proposal.reason} · Evidence: {proposal.evidence_refs.join(', ')} · Reversible: {String(proposal.reversible)}</p><button className="btn btn-primary" onClick={() => void confirm()}>Confirm</button><button onClick={() => setProposal(null)}>Cancel</button></section>}{writeResult && <p role="status">{writeResult}</p>}
    <hr /><h4>Customer capture</h4><p>Paste text or select one image, then explicitly analyze. Selecting does not call a provider.</p><textarea aria-label="Capture text" value={captureText} onChange={event => setCaptureText(event.target.value)} rows={2} style={{ width: '100%' }} /><button onClick={() => void analyzeCapture('text', captureText)} disabled={state !== 'idle' || !captureText.trim()}>Analyze capture</button><input aria-label="Capture image" type="file" accept="image/*" onChange={event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setImagePreview(String(reader.result)); reader.readAsDataURL(file); }} />{imagePreview && <div><img src={imagePreview} alt="Selected customer capture" style={{ maxWidth: 240, maxHeight: 180 }} /><button onClick={() => setImagePreview('')}>Remove image</button><button onClick={() => void analyzeCapture('image', imagePreview)} disabled={state !== 'idle'}>Analyze image</button></div>}
    {captureReview && <div aria-label="Capture fact review"><p>Provider: {captureReview.provider_kind} · Review required</p>{captureReview.facts.map(fact => <article key={fact.fact_id}><strong>{fact.fact_type}</strong> ({fact.confidence}): {fact.reviewed_content} <small>{fact.source_reference} · {fact.review_status}</small><button onClick={() => setCaptureReview(setFactReview(captureReview, fact.fact_id, 'accepted'))}>Accept</button><button onClick={() => setCaptureReview(setFactReview(captureReview, fact.fact_id, 'rejected'))}>Reject</button><input aria-label={`Edit ${fact.fact_id}`} value={editing[fact.fact_id] ?? fact.reviewed_content} onChange={event => setEditing({ ...editing, [fact.fact_id]: event.target.value })} /><button onClick={() => setCaptureReview(editFact(captureReview, fact.fact_id, editing[fact.fact_id] ?? fact.reviewed_content))}>Save edit</button></article>)}<p>Final reviewed facts: {reviewedFacts(captureReview).length}</p><button onClick={() => void analyzeReviewed()} disabled={reviewedFacts(captureReview).length === 0}>Analyze reviewed facts with Sales Agent</button><button onClick={() => { void session.createProposalFromReviewedFacts(captureReview).then(setProposal).catch(cause => setError(cause instanceof Error ? cause.message : String(cause))); }} disabled={reviewedFacts(captureReview).length === 0}>Create CRM proposal from reviewed facts</button></div>}
  </section>;
}
