import { SALES_AGENT_TOOL_REGISTRY, type SalesAgentReadToolContext, type SalesAgentToolId, type SalesAgentToolResult, executeSalesAgentReadTool } from './registry';
import { runSalesAgentRuntime } from '../salesAgent/runtime'; import { createMockReasoningProvider } from '../salesAgent/provider'; import type { SalesAgentRuntimeResult } from '../salesAgent/types';
export interface SalesAgentPlanStep { readonly tool_id: SalesAgentToolId; readonly customer_id: string; }
export interface SalesAgentPlan { readonly kind: 'SALES_AGENT_PLAN'; readonly steps: readonly SalesAgentPlanStep[]; readonly max_steps: 5; }
export interface SalesAgentInteractionResult { readonly plan: SalesAgentPlan; readonly trace: readonly SalesAgentToolResult[]; readonly runtime: SalesAgentRuntimeResult; readonly evidence_refs: readonly string[]; readonly requires_human_review: true; readonly executable: false; readonly writes_crm: false; }
export function validateSalesAgentPlan(plan: SalesAgentPlan, customerId: string): void { if (!Array.isArray(plan.steps) || plan.steps.length === 0 || plan.steps.length > 5) throw new Error('Sales Agent plan must contain one to five steps.'); plan.steps.forEach(step => { const toolId = step.tool_id as SalesAgentToolId; if (!SALES_AGENT_TOOL_REGISTRY[toolId]) throw new Error('Sales Agent plan contains an unknown tool.'); if (step.customer_id !== customerId) throw new Error('Sales Agent plan arguments must preserve current customer scope.'); }); }
export function proposeSalesAgentPlan(message: string, customerId: string): SalesAgentPlan { if (!message.trim()) throw new Error('A user message is required before Sales Agent reasoning.'); return { kind: 'SALES_AGENT_PLAN', max_steps: 5, steps: [{ tool_id: 'get_customer_context', customer_id: customerId }, { tool_id: 'get_active_memory', customer_id: customerId }, { tool_id: 'get_customer_timeline', customer_id: customerId }] }; }
export async function runSalesAgentInteraction(message: string, input: SalesAgentReadToolContext & { profile_id: string }): Promise<SalesAgentInteractionResult> { const plan = proposeSalesAgentPlan(message, input.customer_id); validateSalesAgentPlan(plan, input.customer_id); const trace = plan.steps.map(step => executeSalesAgentReadTool(step.tool_id, input)); const runtime = await runSalesAgentRuntime({ request_id: `${input.context.snapshotId}:sales-agent-interaction`, objective: message, context: input.context, memory: input.memory, profile_id: input.profile_id, provider: createMockReasoningProvider() }); return { plan, trace, runtime, evidence_refs: [...new Set(trace.flatMap(item => item.evidence_refs))], requires_human_review: true, executable: false, writes_crm: false }; }
export type DraftKind = 'follow_up_wording' | 'customer_summary' | 'call_preparation' | 'visit_preparation';
export function createSalesAgentDraft(kind: DraftKind, interaction: SalesAgentInteractionResult) { return { kind, content: interaction.runtime.result.customer_summary.value, evidence_refs: interaction.evidence_refs, requires_human_review: true as const, sent: false as const, written: false as const }; }
export function proposeConfirmedCrmAction(interaction: SalesAgentInteractionResult) { return { proposal_only: true as const, requires_human_confirmation: true as const, executable: false as const, writes_crm: false as const, evidence_refs: interaction.evidence_refs }; }
