import type { LiveProviderSandboxCallResult } from '../liveProviderSandboxCallReadiness';
import type { ManualLiveProviderSmokeResult } from '../manualLiveProviderSmokeGateReadiness';
import type { LiveSandboxToSuggestOnlyBridgeRequest } from '../liveSandboxToSuggestOnlyBridgeReadiness';

interface BridgeFixtureOptions {
  request_id?: string;
  source_kind?: LiveSandboxToSuggestOnlyBridgeRequest['source_kind'];
  source_manual_smoke_result?: ManualLiveProviderSmokeResult;
  source_sandbox_call_result?: LiveProviderSandboxCallResult;
  allow_network?: boolean;
  allow_model_call?: boolean;
  allow_env_read?: boolean;
  allow_db?: boolean;
  allow_runner?: boolean;
  allow_execution?: boolean;
  allow_review_queue_entry?: boolean;
  allow_confirmed_action?: boolean;
  allow_human_confirmation?: boolean;
  allow_write_plan_entry?: boolean;
}

export function buildLiveSandboxToSuggestOnlyBridgeRequestFixtureV1(
  options: BridgeFixtureOptions = {},
): LiveSandboxToSuggestOnlyBridgeRequest {
  const sourceKind = options.source_kind ?? 'manual_live_provider_smoke';
  const manual = options.source_manual_smoke_result
    ?? (sourceKind === 'manual_live_provider_smoke' ? buildManualLiveProviderSmokeResultFixtureV1() : undefined);
  const sandbox = options.source_sandbox_call_result
    ?? (sourceKind === 'live_provider_sandbox_call' ? buildLiveProviderSandboxCallResultFixtureV1() : undefined);

  return {
    kind: 'LIVE_SANDBOX_TO_SUGGEST_ONLY_BRIDGE_REQUEST',
    version: 'v1',
    request_id: options.request_id ?? 'LOOP_51_BRIDGE_FIXTURE_REQUEST_A',
    source_kind: sourceKind,
    bridge_only: true,
    caller_provided_only: true,
    source_manual_smoke_result: manual,
    source_sandbox_call_result: sandbox,
    allow_network: (options.allow_network ?? false) as false,
    allow_model_call: (options.allow_model_call ?? false) as false,
    allow_env_read: (options.allow_env_read ?? false) as false,
    allow_db: (options.allow_db ?? false) as false,
    allow_runner: (options.allow_runner ?? false) as false,
    allow_execution: (options.allow_execution ?? false) as false,
    allow_review_queue_entry: (options.allow_review_queue_entry ?? false) as false,
    allow_confirmed_action: (options.allow_confirmed_action ?? false) as false,
    allow_human_confirmation: (options.allow_human_confirmation ?? false) as false,
    allow_write_plan_entry: (options.allow_write_plan_entry ?? false) as false,
  };
}

export function buildManualLiveProviderSmokeResultFixtureV1(
  outputText = 'Manual smoke redacted bridge output for suggestion review.',
): ManualLiveProviderSmokeResult {
  return {
    kind: 'MANUAL_LIVE_PROVIDER_SMOKE_RESULT',
    version: 'v1',
    plan: {
      kind: 'MANUAL_LIVE_PROVIDER_SMOKE_PLAN',
      version: 'v1',
      manual_only: true,
      sandbox_only: true,
      executable: false,
      persisted: false,
      request: {
        kind: 'MANUAL_LIVE_PROVIDER_SMOKE_REQUEST',
        version: 'v1',
        request_id: 'MANUAL_SMOKE_SOURCE_REQUEST_A',
        user_explicitly_authorized_live_call: true,
        authorization_phrase: 'RUN_ONE_MANUAL_LIVE_PROVIDER_SMOKE',
        provider_config: {
          provider_kind: 'openai_compatible',
          endpoint_url_redacted: '[REDACTED_ENDPOINT]',
          model_name: 'manual-smoke-readiness-model',
          api_key_reference: '[REDACTED_REFERENCE]',
          api_key_resolved: true,
          resolved_by: 'injected_secret_resolver',
          exposes_secret: false,
          prints_secret: false,
        },
        prompt_input: {
          kind: 'MANUAL_LIVE_PROVIDER_SMOKE_PROMPT_INPUT',
          text: 'redacted manual bridge prompt',
          contains_pii: false,
          contains_secret: false,
          from_database: false,
          from_crm_customer: false,
          trusted_for_action: false,
        },
        safety_policy: {
          redact_prompt: true,
          redact_response: true,
          max_output_chars: 200,
          timeout_ms: 1000,
          allow_persistence: false,
          allow_action_generation: false,
          allow_review_queue_entry: false,
          allow_db_write: false,
        },
        allow_network: true,
        allow_live_provider: true,
        allow_env_read: false,
        allow_db: false,
        allow_runner: false,
        allow_execution: false,
        allow_review_queue_entry: false,
        allow_confirmed_action: false,
        allow_human_confirmation: false,
        allow_write_plan_entry: false,
        dry_run_default: true,
      },
      sandbox_request: {
        kind: 'LIVE_PROVIDER_SANDBOX_CALL_REQUEST',
        version: 'v1',
        request_id: 'MANUAL_SMOKE_SOURCE_REQUEST_A',
        prompt_input: {
          kind: 'LIVE_PROVIDER_SANDBOX_PROMPT_INPUT',
          text: 'redacted manual bridge prompt',
          contains_pii: false,
          contains_secret: false,
          from_database: false,
          from_crm_customer: false,
          trusted_for_action: false,
        },
        provider_config: {
          provider_kind: 'openai_compatible',
          endpoint_url_redacted: '[REDACTED_ENDPOINT]',
          model_name: 'manual-smoke-readiness-model',
          api_key_reference: '[REDACTED_REFERENCE]',
          api_key_resolved: true,
          exposes_secret: false,
          prints_secret: false,
          resolved_by: 'injected_secret_resolver',
        },
        safety_policy: {
          redact_prompt: true,
          redact_response: true,
          max_output_chars: 200,
          timeout_ms: 1000,
          allow_persistence: false,
          allow_action_generation: false,
          allow_review_queue_entry: false,
          allow_db_write: false,
        },
        allow_live_call: true,
        allow_network: true,
        allow_env_read: false,
        allow_db: false,
        allow_runner: false,
        allow_execution: false,
        allow_review_queue_entry: false,
        allow_confirmed_action: false,
        allow_human_confirmation: false,
        allow_write_plan_entry: false,
      },
    },
    answer: {
      kind: 'MANUAL_LIVE_PROVIDER_SMOKE_ANSWER',
      smoke_gate_only: true,
      manual_only: true,
      sandbox_only: true,
      authorization_accepted: true,
      provider_kind: 'openai_compatible',
      model_name: 'manual-smoke-readiness-model',
      response_envelope: {
        kind: 'MANUAL_LIVE_PROVIDER_SMOKE_RESPONSE_ENVELOPE',
        sandbox_only: true,
        manual_smoke_only: true,
        live_provider_response: true,
        output_text_redacted: outputText,
        raw_output_stored: false,
        contains_secret: false,
        contains_pii: false,
        trusted_for_action: false,
        executable: false,
        produces_proposal: false,
        enters_review_queue: false,
        persisted: false,
      },
      error_envelope: null,
      safety_summary: {
        kind: 'MANUAL_LIVE_PROVIDER_SMOKE_SAFETY_SUMMARY',
        prompt_redacted: true,
        response_redacted: true,
        persistence_allowed: false,
        action_generation_allowed: false,
        review_queue_entry_allowed: false,
        db_write_allowed: false,
      },
      trace_summary: {
        kind: 'MANUAL_LIVE_PROVIDER_SMOKE_TRACE_SUMMARY',
        request_id: 'MANUAL_SMOKE_SOURCE_REQUEST_A',
        provider_kind: 'openai_compatible',
        secret_resolved: true,
        secret_resolved_by: 'injected_secret_resolver',
        transport_mode: 'live_capable',
        sandbox_only: true,
        manual_only: true,
        persisted: false,
      },
      output_text_redacted: outputText,
      raw_output_available: false,
      raw_output_stored: false,
      persisted: false,
      enters_review_queue: false,
      produces_confirmed_action: false,
      produces_executable_proposal: false,
      writes_database: false,
      calls_runner: false,
    },
    persisted: false,
    reads_database: false,
    writes_database: false,
    reads_env: false,
    uses_network: true,
    calls_real_provider: true,
    manual_live_smoke_attempted: true,
    manual_live_smoke_succeeded: true,
    represents_model_output: true,
    represents_live_model_call: true,
    represents_executed_action: false,
    represents_confirmed_action: false,
    represents_review_queue_entry: false,
    represents_human_confirmation: false,
    represents_write_plan: false,
  };
}

export function buildLiveProviderSandboxCallResultFixtureV1(
  outputText = 'Sandbox redacted bridge output for suggestion review.',
): LiveProviderSandboxCallResult {
  return {
    kind: 'LIVE_PROVIDER_SANDBOX_CALL_RESULT',
    version: 'v1',
    plan: {
      kind: 'LIVE_PROVIDER_SANDBOX_CALL_PLAN',
      version: 'v1',
      sandbox_only: true,
      executable: false,
      persisted: false,
      request: {
        kind: 'LIVE_PROVIDER_SANDBOX_CALL_REQUEST',
        version: 'v1',
        request_id: 'SANDBOX_SOURCE_REQUEST_A',
        prompt_input: {
          kind: 'LIVE_PROVIDER_SANDBOX_PROMPT_INPUT',
          text: 'redacted sandbox bridge prompt',
          contains_pii: false,
          contains_secret: false,
          from_database: false,
          from_crm_customer: false,
          trusted_for_action: false,
        },
        provider_config: {
          provider_kind: 'local_fake',
          endpoint_url_redacted: '[REDACTED_ENDPOINT]',
          model_name: 'sandbox-readiness-model',
          api_key_reference: '[REDACTED_REFERENCE]',
          api_key_resolved: true,
          exposes_secret: false,
          prints_secret: false,
          resolved_by: 'test_fake',
        },
        safety_policy: {
          redact_prompt: true,
          redact_response: true,
          max_output_chars: 200,
          timeout_ms: 1000,
          allow_persistence: false,
          allow_action_generation: false,
          allow_review_queue_entry: false,
          allow_db_write: false,
        },
        allow_live_call: false,
        allow_network: false,
        allow_env_read: false,
        allow_db: false,
        allow_runner: false,
        allow_execution: false,
        allow_review_queue_entry: false,
        allow_confirmed_action: false,
        allow_human_confirmation: false,
        allow_write_plan_entry: false,
      },
      allowed_operations: [
        'validate_caller_provided_sandbox_request',
        'resolve_secret_through_caller_seam',
        'invoke_caller_provided_transport',
        'build_sandbox_response_envelope',
      ],
      forbidden_operations: [],
    },
    answer: {
      kind: 'LIVE_PROVIDER_SANDBOX_CALL_ANSWER',
      sandbox_only: true,
      live_call_attempted: false,
      live_call_succeeded: true,
      provider_kind: 'local_fake',
      model_name: 'sandbox-readiness-model',
      response_envelope: {
        kind: 'LIVE_PROVIDER_SANDBOX_RESPONSE_ENVELOPE',
        sandbox_only: true,
        live_provider_response: false,
        output_text_redacted: outputText,
        raw_output_stored: false,
        contains_secret: false,
        contains_pii: false,
        trusted_for_action: false,
        executable: false,
        produces_proposal: false,
        enters_review_queue: false,
        persisted: false,
      },
      error_envelope: null,
      safety_summary: {
        kind: 'LIVE_PROVIDER_SANDBOX_SAFETY_SUMMARY',
        prompt_redacted: true,
        response_redacted: true,
        persistence_allowed: false,
        action_generation_allowed: false,
        review_queue_entry_allowed: false,
        db_write_allowed: false,
      },
      trace_summary: {
        kind: 'LIVE_PROVIDER_SANDBOX_TRACE_SUMMARY',
        request_id: 'SANDBOX_SOURCE_REQUEST_A',
        provider_kind: 'local_fake',
        transport_mode: 'fake',
        validation_checked: true,
        secret_resolved_by: 'test_fake',
        sandbox_only: true,
        persisted: false,
      },
      output_text_redacted: outputText,
      raw_output_available: false,
      persisted: false,
      enters_review_queue: false,
      produces_confirmed_action: false,
      produces_executable_proposal: false,
      writes_database: false,
      calls_runner: false,
    },
    persisted: false,
    reads_database: false,
    writes_database: false,
    reads_env: false,
    uses_network: false,
    calls_real_provider: false,
    represents_model_output: true,
    represents_live_model_call: false,
    represents_executed_action: false,
    represents_confirmed_action: false,
    represents_review_queue_entry: false,
    represents_human_confirmation: false,
    represents_write_plan: false,
  };
}
