export type CaptureSourceType = 'text' | 'image';
export type VisualFactType = 'extracted_text' | 'visible_product_attribute' | 'company_contact_information' | 'visible_requirement' | 'visible_objection' | 'document_field' | 'date_quantity_specification' | 'manual_review_required';
export type CaptureReviewStatus = 'pending' | 'accepted' | 'rejected' | 'edited';
export interface CaptureFact { readonly fact_id: string; readonly fact_type: VisualFactType; readonly content: string; readonly original_content: string; readonly reviewed_content: string; readonly review_status: CaptureReviewStatus; readonly source_reference: string; readonly confidence: number; readonly provider_kind: 'DEEPSEEK_COMPATIBLE' | 'QWEN_VISION_COMPATIBLE' | 'DETERMINISTIC_LOCAL'; readonly edited_by_user: boolean; readonly location?: string; }
export interface CustomerCaptureReview { readonly customer_id: string; readonly source_type: CaptureSourceType; readonly facts: readonly CaptureFact[]; readonly provider_kind: CaptureFact['provider_kind']; readonly runtime_metadata?: ProductionRuntimeDetails; readonly reviewed: false; readonly writes_crm: false; }
const factTypes: readonly VisualFactType[] = ['extracted_text', 'visible_product_attribute', 'company_contact_information', 'visible_requirement', 'visible_objection', 'document_field', 'date_quantity_specification', 'manual_review_required'];
export function validateCaptureFacts(value: unknown, customerId: string): readonly Omit<CaptureFact, 'original_content' | 'reviewed_content' | 'review_status' | 'provider_kind' | 'edited_by_user'>[] { if (!Array.isArray(value) || !customerId.trim()) throw new Error('Customer-scoped capture facts are required.'); return value.map(fact => { if (!record(fact) || Object.keys(fact).some(key => !['fact_id', 'fact_type', 'content', 'source_reference', 'confidence', 'location'].includes(key)) || !factTypes.includes(fact.fact_type as VisualFactType) || !text(fact.fact_id) || !text(fact.content) || !text(fact.source_reference) || typeof fact.confidence !== 'number' || fact.confidence < 0 || fact.confidence > 1 || (fact.location !== undefined && !text(fact.location))) throw new Error('Unsafe or invalid capture fact.'); return { fact_id: fact.fact_id as string, fact_type: fact.fact_type as VisualFactType, content: fact.content as string, source_reference: fact.source_reference as string, confidence: fact.confidence as number, ...(fact.location ? { location: fact.location as string } : {}) }; }); }
export function createUnreviewedCapture(customerId: string, sourceType: CaptureSourceType, providerKind: CustomerCaptureReview['provider_kind'], facts: unknown, runtimeMetadata?: ProductionRuntimeDetails): CustomerCaptureReview { return { customer_id: customerId, source_type: sourceType, provider_kind: providerKind, facts: validateCaptureFacts(facts, customerId).map(fact => ({ fact_id: fact.fact_id, fact_type: fact.fact_type, content: fact.content, original_content: fact.content, reviewed_content: fact.content, review_status: 'pending', source_reference: fact.source_reference, confidence: fact.confidence, provider_kind: providerKind, edited_by_user: false, ...(fact.location ? { location: fact.location } : {}) })), ...(runtimeMetadata ? { runtime_metadata: runtimeMetadata } : {}), reviewed: false, writes_crm: false }; }
export function setFactReview(review: CustomerCaptureReview, factId: string, status: Exclude<CaptureReviewStatus, 'edited'>, editedContent?: string): CustomerCaptureReview { const facts = review.facts.map(fact => fact.fact_id !== factId ? fact : status === 'accepted' ? { ...fact, review_status: status } : status === 'rejected' ? { ...fact, review_status: status } : { ...fact, reviewed_content: editedContent ?? fact.reviewed_content, review_status: 'edited' as const, edited_by_user: true }); return { ...review, facts }; }
export function editFact(review: CustomerCaptureReview, factId: string, content: string): CustomerCaptureReview { if (!content.trim()) throw new Error('Reviewed fact content is required.'); return setFactReview(review, factId, 'accepted', content).facts === review.facts ? review : { ...review, facts: review.facts.map(fact => fact.fact_id === factId ? { ...fact, reviewed_content: content.trim(), review_status: 'edited', edited_by_user: true } : fact) }; }
export function reviewedFacts(review: CustomerCaptureReview): readonly CaptureFact[] { return review.facts.filter(fact => fact.review_status === 'accepted' || fact.review_status === 'edited'); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; } function text(value: unknown): value is string { return typeof value === 'string' && value.trim().length > 0; }
import type { ProductionRuntimeDetails } from '../productionAi/runtimeMode';
